export const TERMS_FACTORY_ABI = [
  {
    inputs: [
      { name: '_usdc', type: 'address' },
      { name: '_feeCollector', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      { name: 'invoiceId', type: 'bytes32' },
      { name: 'termsHash', type: 'bytes32' },
      { name: 'deliverableAmounts', type: 'uint256[]' },
      { name: 'criteriaHashes', type: 'bytes32[]' },
      { name: 'deadlineDays', type: 'uint256[]' },
      { name: 'autoReleaseDays', type: 'uint256' },
    ],
    name: 'createEscrow',
    outputs: [{ name: 'escrowAddress', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'invoiceId', type: 'bytes32' }],
    name: 'getEscrow',
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getEscrowCount',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'index', type: 'uint256' }],
    name: 'getEscrowByIndex',
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'usdc',
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'feeCollector',
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'invoiceId', type: 'bytes32' },
      { indexed: true, name: 'escrow', type: 'address' },
      { indexed: true, name: 'creator', type: 'address' },
      { indexed: false, name: 'termsHash', type: 'bytes32' },
      { indexed: false, name: 'totalAmount', type: 'uint256' },
      { indexed: false, name: 'deliverableCount', type: 'uint256' },
    ],
    name: 'EscrowCreated',
    type: 'event',
  },
] as const;

export const TERMS_ESCROW_ABI = [
  // State reading
  {
    inputs: [],
    name: 'state',
    outputs: [{ type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'creator',
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'payer',
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'termsHash',
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalAmount',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fundedAmount',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'releasedAmount',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fundedAt',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'autoReleaseDays',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'currentDeliverable',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getDetails',
    outputs: [
      { name: '_creator', type: 'address' },
      { name: '_payer', type: 'address' },
      { name: '_termsHash', type: 'bytes32' },
      { name: '_totalAmount', type: 'uint256' },
      { name: '_fundedAmount', type: 'uint256' },
      { name: '_releasedAmount', type: 'uint256' },
      { name: '_state', type: 'uint8' },
      { name: '_fundedAt', type: 'uint256' },
      { name: '_autoReleaseDays', type: 'uint256' },
      { name: '_deliverableCount', type: 'uint256' },
      { name: '_currentDeliverable', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'index', type: 'uint256' }],
    name: 'getDeliverable',
    outputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'criteriaHash', type: 'bytes32' },
      { name: 'deadlineDays', type: 'uint256' },
      { name: 'funded', type: 'bool' },
      { name: 'approved', type: 'bool' },
      { name: 'disputed', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getDeliverableCount',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'canAutoRelease',
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  // Mutations
  {
    inputs: [{ name: 'signature', type: 'bytes' }],
    name: 'signTerms',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'index', type: 'uint256' }],
    name: 'fundDeliverable',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'index', type: 'uint256' }],
    name: 'approveDeliverable',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'index', type: 'uint256' },
      { name: 'reason', type: 'string' },
    ],
    name: 'disputeDeliverable',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'index', type: 'uint256' },
      { name: 'payerAmount', type: 'uint256' },
    ],
    name: 'resolveDispute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'refund',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'autoRelease',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'payer', type: 'address' },
      { indexed: false, name: 'signatureHash', type: 'bytes32' },
    ],
    name: 'TermsSigned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'index', type: 'uint256' },
      { indexed: true, name: 'payer', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'DeliverableFunded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'index', type: 'uint256' },
      { indexed: false, name: 'creatorAmount', type: 'uint256' },
      { indexed: false, name: 'fee', type: 'uint256' },
    ],
    name: 'DeliverableApproved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'index', type: 'uint256' },
      { indexed: false, name: 'reason', type: 'string' },
    ],
    name: 'DeliverableDisputed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'index', type: 'uint256' },
      { indexed: false, name: 'payerAmount', type: 'uint256' },
      { indexed: false, name: 'creatorAmount', type: 'uint256' },
    ],
    name: 'DisputeResolved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'recipient', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'Refunded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'FullyCompleted',
    type: 'event',
  },
] as const;

// EscrowState enum mapping
export const EscrowState = {
  CREATED: 0,
  SIGNED: 1,
  ACTIVE: 2,
  COMPLETED: 3,
  REFUNDED: 4,
} as const;

export type EscrowStateType = (typeof EscrowState)[keyof typeof EscrowState];
